// Mock handoff card data
export const MOCK_HANDOFF_CARDS = [
    {
        id: 'H001',
        patientName: 'Ravi Sharma',
        patientId: 'P001',
        ward: 'General Ward',
        bed: 'Bed 12A',
        doctorName: 'Dr. Mehta',
        nurseName: 'Nurse Anjali',
        shift: 'Morning',
        shiftTime: '8:00 AM – 4:00 PM',
        shiftDate: '2026-04-11',
        colorStatus: 'green',
        vitals: {
            bloodPressure: '120/80 mmHg',
            heartRate: '72 bpm',
            temperature: '98.6°F',
            respiratoryRate: '16 breaths/min',
            oxygenSaturation: '98%',
            sugarLevel: '90 mg/dL',
        },
        medications: [
            { name: 'Metformin 500mg', currentMed: true, nextDose: '12:00 PM', missedDose: false },
            { name: 'Atorvastatin 10mg', currentMed: true, nextDose: '9:00 PM', missedDose: false },
        ],
        medicationStartDate: '2026-03-15',
        notes: 'Patient is stable. Continue regular monitoring. No complaints.',
        pendingActions: [],
    },
    {
        id: 'H002',
        patientName: 'Arjun Desai',
        patientId: 'P003',
        ward: 'ICU',
        bed: 'Bed 3',
        doctorName: 'Dr. Kulkarni',
        nurseName: 'Nurse Pradeep',
        shift: 'Evening',
        shiftTime: '4:00 PM – 12:00 AM',
        shiftDate: '2026-04-11',
        colorStatus: 'red',
        vitals: {
            bloodPressure: '160/100 mmHg',
            heartRate: '102 bpm',
            temperature: '101.4°F',
            respiratoryRate: '24 breaths/min',
            oxygenSaturation: '88%',
            sugarLevel: '210 mg/dL',
        },
        medications: [
            { name: 'Insulin Glargine', currentMed: true, nextDose: '6:00 PM', missedDose: true },
            { name: 'Amlodipine 5mg', currentMed: true, nextDose: '8:00 PM', missedDose: false },
        ],
        medicationStartDate: '2026-04-07',
        notes: 'Patient in critical condition. Oxygen support active. Immediate attention required.',
        pendingActions: ['Missed dose alert for Insulin Glargine', 'Blood culture report pending', 'Notify cardiologist on call'],
    },
    {
        id: 'H004',
        patientName: 'Neha Singh',
        patientId: 'P004',
        ward: 'Emergency',
        bed: 'Bed 1A',
        doctorName: 'Dr. Iyer',
        nurseName: 'Nurse Pooja',
        shift: 'Morning',
        shiftTime: '8:00 AM – 4:00 PM',
        shiftDate: '2026-04-11',
        colorStatus: 'red',
        vitals: {
            bloodPressure: '150/95 mmHg',
            heartRate: '110 bpm',
            temperature: '101.2°F',
            respiratoryRate: '22 breaths/min',
            oxygenSaturation: '90%',
            sugarLevel: '160 mg/dL',
        },
        medications: [
            { name: 'IV Fluids', currentMed: true, nextDose: 'Ongoing', missedDose: false },
            { name: 'Antibiotics', currentMed: true, nextDose: '2:00 PM', missedDose: false },
        ],
        medicationStartDate: '2026-04-10',
        notes: 'Critical condition. Under observation.',
        pendingActions: ['CT Scan', 'Specialist consultation'],
    },
    {
        id: 'H005',
        patientName: 'Rahul Deshmukh',
        patientId: 'P005',
        ward: 'General Ward',
        bed: 'Bed 9D',
        doctorName: 'Dr. Kulkarni',
        nurseName: 'Nurse Sneha',
        shift: 'Evening',
        shiftTime: '4:00 PM – 12:00 AM',
        shiftDate: '2026-04-11',
        colorStatus: 'yellow',
        vitals: {
            bloodPressure: '135/88 mmHg',
            heartRate: '82 bpm',
            temperature: '99.5°F',
            respiratoryRate: '17 breaths/min',
            oxygenSaturation: '96%',
            sugarLevel: '120 mg/dL',
        },
        medications: [
            { name: 'Amoxicillin', currentMed: true, nextDose: '6:00 PM', missedDose: false },
            { name: 'Ibuprofen', currentMed: false, nextDose: '—', missedDose: true },
        ],
        medicationStartDate: '2026-04-05',
        notes: 'Missed one dose. Monitor compliance.',
        pendingActions: ['Counsel patient on medication adherence'],
    }
]
